const ShopActionTypes = {
	FETCHING_COLLECTIONS_START: "FETCHING_COLLECTIONS_START",
	FETCHING_COLLECTIONS_SUCCESS: "FETCHING_COLLECTIONS_SUCCESS",
	FETCHING_COLLECTIONS_FAILED: "FETCHING_COLLECTIONS_FAILED"
};

export default ShopActionTypes;
